/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

INSERT INTO `ecole` (`id`, `codeEcole`, `nameEcole`, `isactive`) VALUES
(1,'ASE','African School of Economics',1),
(2,'AU','Afriford University ',1),
(3,'CECG','Centre d\'Etude Commerciale et de Gestion',1),
(4,'CET-AAT IPAM','Centre d\'Études Touristiques de l\'Agence Africaine de Tourisme',1),
(5,'CFRMP','Centre de Formation et de Recherche en Matière de Population',1),
(6,'CEFOREC','Centre de Formation et de Recyclage',1),
(7,'PROVIDENCE','Centre de Formation Professionnelle « LA PROVIDENCE » ',1),
(8,'CFPMM','Centre de Formation Professionnelle aux Métiers des Médias',1),
(9,'CIFREDD','Centre InterFacultaire de Formation et de Recherche en Environnement pour le Développement Durable',1),
(10,'CPFCC','Centre Panafricain de Formation Coopérative de Cotonou',1),
(11,'CePUC','Centre Polytechnique Universitaire de Cotonou ',1),
(12,'CIPMA','Chaire Internationale de Physiques et de Mathématiques Appliquées',1),
(13,'Cepib','Complexe d\'Enseignement Polytechnique Internartional du Bénin',1),
(14,'Master Soft','Ecole de BTS Master Schools ',1),
(15,'SAPIENTIA','Ecole de Formation des Enseignants du Secondaire SAPIENTIA',1),
(16,'EHT','Ecole de Hautes Technologies',1),
(17,'ECOTES','Ecole de Techniciens Supérieurs La GRÂCE',1),
(18,'ETS KVT','Ecole de Technologie Supérieure Karl Von Terzaghi',1),
(19,'EC','Ecole des Cadres ',1),
(20,'EDSAE','Ecole Doctorale EDSAE',1),
(21,'ENSPD','Ecole National des Statistiques et de la Planification Démographique',1),
(22,'ENSAP','Ecole National Supérieure Agro Pastorale',1),
(23,'ENSAGAP','Ecole National Supérieure de l\'Aménagement et Gestion des Aires Protégés',1),
(24,'ENAM','Ecole Nationale d\'Administration et de Magistrature',1),
(25,'ENEAM','Ecole Nationale d\'Economie Appliquée et Management',1),
(26,'ENS','Ecole Normale Supérieure',1),
(27,'EPAC','Ecole Polytechnique d\'Abomey-Calavi',1),
(28,'POLYTECH-ADA','École Polytechnique des Génies',1),
(29,'EPS-CITE','Ecole Professionnelle Spécialisée -LA CITÉ',1),
(30,'ESIGT','Ecole Supérieur d\'Ingénieur Géomètre Topographe',1),
(31,'VERECHAGUINE A.K.','Ecole Supérieur de Génie Civile',1),
(32,'ESCSS','Ecole Supérieure Catholique des Sciences de la Santé',1),
(33,'ESAE','Ecole Supérieure d\'Administration d\'Economie de Journalisme et des métiers de l\'Audiovisuel',1),
(34,'ESEP-BERGER','Ecole Supérieure d\'Enseignement Professionnel le Berger',1),
(35,'ESIC','Ecole Supérieure d\'Ingénierie du Commerce ',1),
(36,'ESCAE-Bénin','Ecole Supérieure de commerce et d\'Administration des Entreprises du Bénin',1),
(37,'ESGIS','Ecole Supérieure de Gestion d\'Informatique et de Sciences',1),
(38,'ESG-SERENA','Ecole Supérieure de Gestion SERENA',1),
(39,'ESM','Ecole Supérieure de Management ',1),
(40,'ESTIM','École Supérieure de Techniques Industrielles et de Management',1),
(41,'ESTG','Ecole Supérieure de technologie et de Gestion',1),
(42,'ESTG-Exc','Ecole Supérieure de Technologie et de Gestion « L\'Excellence » ',1),
(43,'EST-IFFA','Ecole Supérieure de technologie IFFA',1),
(44,'ESTA','Ecole Supérieure des Techniques d\'Avenir',1),
(45,'ESP','Ecole Supérieure la Prophétie',1),
(46,'ES-FAUCON','Ecole Supérieure Le FAUCON',1),
(47,'ESPAM','Ecole Supérieure Panafricaine de Management Appliquée ',1),
(48,'EPSO','Ecole Supérieure Polytechnique ',1),
(49,'ESSL','Ecole supérieure Saint Louis',1),
(50,'ESSF','Ecole Supérieure Sainte Félicité',1),
(51,'ESPERANZA','ESPERANZA',1),
(52,'FA','Faculté d\'Agronomie',1),
(53,'FDSP TCHAOUROU','Faculté de Droit et de Science Politique de Tchaourou',1),
(54,'FDSP-parak','Faculté de Droit et de Science Politique Parakou',1),
(55,'FDSP','Faculté de Droit et des Science Politique',1),
(56,'FM','Faculté de Médécine',1),
(57,'FLASH','Faculté des Arts et Sciences Humaines',1),
(58,'FSSH','Faculté des Sciences Agronomiques',1),
(59,'FSASH','Faculté des Sciences Art et Sciences Humaines',1),
(60,'FaSEG','Faculté des Sciences Economiques et de Gestion',1),
(61,'FASEG SAVE','Faculté des Sciences Economiques et de Gestion de Savè',1),
(62,'FASEG PARAKOU','Faculté des Sciences Economiques et de Gestion Parakou',1),
(63,'FSA','Faculté des Sciences et Santé',1),
(64,'FST','Faculté des Sciences Techniques',1),
(65,'FSS','Filière de Musique',1),
(66,'BK','Groupe BK Université ',1),
(67,'HECM','Haute Ecole de Commerce et de Management ',1),
(68,'HEGJ','Haute École de Gestion et de Journalisme',1),
(69,'HEGT','Haute École de Gestion et de Technologie ',1),
(70,'HERCI','Haute Ecole Régionale de Commerce International',1),
(71,'HEULI-BENIN','Haute Ecole Universitaire Libre du Bénin ',1),
(72,'HNAUB','Houdegbe North American University Bénin',1),
(73,'CERCO','Institut Cerco',1),
(74,'ICO','Institut Cinématographique de Ouidah ',1),
(75,'ICBA','Institut de Chimie et de Biologie Appliquées',1),
(76,'IFSIO','Institut de Formation des Sage femme et infirmier',1),
(77,'IFRI','Institut de Formation et de Recheche en Informatique',1),
(78,'BOBO','Institut de Formation Professionnelle BOBO ',1),
(79,'ILACI','Institut de Langue Arabe et de Culture Islamique',1),
(80,'IMSP','Institut de Mathématiques et de Sciences Physiques',1),
(81,'IQL','Institut du Quartier Latin ',1),
(82,'IIM','Institut International de Management',1),
(83,'ILEPS','Institut Littoral des Etudes Professionnelles Supérieures ',1),
(84,'INEFM','Institut Nationale de l\'Eau',1),
(85,'IPAFOS','Institut Panafricain de Formation Supérieure ',1),
(86,'IPES-UNION','Institut Polytechnique d\'Enseignement Supérieur de l\'Union ',1),
(87,'(IRES)','Institut Régional d\'Enseignement Supérieur (IRES) du Complexe Scolaire et Universitaire (CSU) Jean Jacques ROUSSEAU ',1),
(88,'IRGIB-AFRICA','Institut Régional du Génie Industriel, des Biotechnologies et Sciences Appliquées',1),
(89,'ISETCSV','Institut Supérieur d\'Enseignement Technique du Complexe Scolaire et Universitaire « Le VERGER » ',1),
(90,'ISET-JACKY','Institut Supérieur d\'Enseignement Technique JACKY',1),
(91,'ISET¬NDA','Institut Supérieur d\'Enseignement Technique Notre Dame d\'Afrique ',1),
(92,'ISEG','Institut Supérieur d\'Expertise et de Gestion',1),
(93,'ISCG','Institut Supérieur de Communication et de Gestion ',1),
(94,'ISFES-LV','Institut Supérieur de Formation des Évaluations Spécialisées Laura-Vicuna',1),
(95,'ISG','Institut Supérieur de Gestion',1),
(96,'ADONAI','Institut Supérieur de Management ',1),
(97,'Adonaï','Institut Supérieur de Management Adonaï',1),
(98,'ISMA','Institut Supérieur des Métiers de l\'Audiovisuel',1),
(99,'ISST','Institut Supérieur des Sciences et Techniques',1),
(100,'IN-FOPASE','Institut Supérieur Fopase ',1),
(101,'HCUB','Institut Supérieur HCUB',1),
(102,'Ispec','Institut Supérieur Panafricain d\'Economie Coopérative',1),
(103,'IUSEBA','Institut Universitaire de Sciences Économiques et Biologiques Appliquées',1),
(104,'UIT-parak','Institut Universitaire de Technologie Parakou',1),
(105,'IUB','Institut Universitaire du Bénin',1),
(106,'IUP','Institut Universitaire Panafricain',1),
(107,'IU','Intercontinental University',1),
(108,'IRSBAC-COM','IRSBAC-COM/Parakou',1),
(109,'KAU','KING AMACHREE University ',1),
(110,'KUB','Kings University Benin ',1),
(111,'SONOU','Les Cours SONOU',1),
(112,'Royal','Mount Royal ',1),
(113,'PIGIER','PIGIER-BENIN',1),
(114,'Poly-Cit','Polytech Le citoyen',1),
(115,'POMA','Poma International Business University ',1),
(116,'SAPIENTIA','SAPIENTIA',1),
(117,'UATM-GAZA','Université Africaine de Technologie et de Management ',1),
(118,'UCAO','Université Catholique de l\'Afrique de l\'Ouest',1),
(119,'UAC','Université d\'Abomey-Calavi',1),
(120,'UP','Université de Parakou',1),
(121,'USTB','Université des Sciences et Technologies du Bénin',1),
(122,'EAK','Université Nationale d\'Agriculture',1),
(123,'UPA','Université polytechnique d\'Abomey',1),
(124,'Upib','Université Polytechnique Internationale du Bénin',1),
(125,'UPI-ONM','Université Polytechnique Internationale Obiang N\'GUEMA',1),
(126,'UPAO','Université Protestante de l\'Afrique de l\'Ouest ',1),
(127,'USAPN','Université Sciences agronomiques de Porto-Novo',1),
(128,'WAUU','West African Union University',1),
(129,'UAK','Université Nationale d’Agriculture de Kétou',1);
